version: '3.8'

services:
  immanuel-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: immanuel-mcp-server
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=8000
      - MCP_SERVER_NAME=immanuel-astrology
      - MCP_SERVER_VERSION=1.0.0
      - DEFAULT_HOUSE_SYSTEM=placidus
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health/').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - immanuel-network

  # Development service
  immanuel-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: immanuel-mcp-dev
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=true
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev
    networks:
      - immanuel-network

  # Reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: immanuel-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - immanuel-mcp-server
    profiles:
      - proxy
    networks:
      - immanuel-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: immanuel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    profiles:
      - cache
    networks:
      - immanuel-network

volumes:
  redis_data:

networks:
  immanuel-network:
    driver: bridge